const uiStrings = {
  ja: {
    // From HTML
    pageTitle: "多機能動画分割ツール v2.6 (ショートカット&スクロール対応)",
    mainHeading: "多機能動画分割ツール v2.2",
    fileDropAreaText: "ここに動画/音声ファイルをドラッグ＆ドロップ、またはクリックして選択",
    playButton: "再生",
    playPauseButtonTitle: "再生/一時停止 (Space)",
    seekBarTitle: "シークバー",
    sequentialModeTabCaption: "逐次分割",
    sequentialModeTabTitle: "逐次分割モード",
    freeModeTabCaption: "自由区間指定",
    freeModeTabTitle: "自由区間指定モード",
    fixedLengthModeTabCaption: "固定長分割",
    fixedLengthModeTabTitle: "固定長分割モード",
    sequentialModeHeading: "逐次分割モード",
    sequentialModeDescription: "動画を再生し、区切りたい位置で下のボタンを押すか <kbd>M</kbd> キーを押してください。",
    markSequentialSplitPointButtonCaption: "現在の位置で分割点をマーク",
    markSequentialSplitPointButtonTitle: "現在の位置で分割点をマーク (M)",
    freeModeHeading: "自由区間指定モード",
    freeModeDescription: "下のボタンで新規区間を追加するか <kbd>N</kbd> キーを押し、開始/終了時間を編集してください。",
    addFreeSegmentButtonCaption: "新規区間を追加",
    addFreeSegmentButtonTitle: "新規区間を追加 (N)",
    fixedLengthModeHeading: "固定長分割モード",
    fixedSegmentLengthLabel: "セグメント長 (秒):",
    fixedStartOffsetLabel: "開始オフセット (秒):",
    previewFixedLengthSegmentsButtonCaption: "固定長セグメントをマーク",
    commonSettingsHeading: "共通設定",
    fileNamePrefixLabel: "ファイル名プレフィックス:",
    audioOnlyModeCheckboxLabel: " 音声のみを抽出・分割する", // Note leading space if it was intended
    audioOnlyModeCheckboxTitle: "音声のみ抽出 (O)",
    markedSegmentsListHeading: "マーク済みセグメントリスト",
    generateAllMarkedButtonCaption: "マーク済全セグメントを生成",
    generateAllMarkedButtonTitle: "マーク済の未生成セグメントを全て生成",
    downloadAllGeneratedButtonCaption: "生成済全セグメントをZIPでダウンロード",
    downloadAllGeneratedButtonTitle: "生成済の全セグメントをZIPでダウンロード",
    cancelCurrentOperationButtonCaption: "現在の操作をキャンセル",
    cancelCurrentOperationButtonTitle: "現在の生成/圧縮処理をキャンセル (Esc)",
    statusInitial: "ステータス: 動画ファイルを選択してください。",
    exportSegmentsButtonCaption: "区間情報をエクスポート",
    exportSegmentsButtonTitle: "現在の区間情報をファイルに保存 (Cmd/Ctrl + S)",
    importSegmentsLabelCaption: "区間情報をインポート",
    importSegmentsLabelTitle: "区間情報ファイルを読み込む (Cmd/Ctrl + O)",
    shortcutHelpText: "ショートカット: Space (再生/一時停止), M (逐次マーク), N (新規区間), Esc (キャンセル)",
    languageSelectorLabel: "言語 (Language):",
    langOptionJapanese: "日本語",
    langOptionEnglish: "English",

    // Dynamically generated/updated by JavaScript
    pauseButton: "一時停止",
    statusSelectedFile: "選択中のファイル: %fileName%",
    statusVideoLoaded: "動画読み込み完了: %fileName% (%duration%)。分割モードを選択し、操作を開始してください。",
    errorVideoLoadFailed: "エラー: 動画ファイルの読み込みに失敗。",
    tooltipSegmentRange: "区間 %segmentIndex%: %startTime% - %endTime%",
    timelineMarkerStartTimeTitle: "区間開始: %time%",
    timelineMarkerEndTimeTitle: "区間終了: %time%",
    errorInvalidStartEndTimes: "開始/終了時間が無効な数値です。",
    errorEndTimeBeforeStartTime: "終了時間 (%endTime%) は開始時間 (%startTime%) より後にしてください。",
    errorStartTimeNegative: "開始時間は0秒以上にしてください。",
    errorEndTimeExceedsDuration: "終了時間が動画の総長 (%duration%) を超えています。",
    statusErrorPrefix: "エラー: %error%", // Generic prefix for errors shown in statusArea
    statusSegmentAdded: "セグメント (%startTime% - %endTime%) を追加しました。",
    statusSegmentUpdated: "セグメント (%startTime% - %endTime%) を更新しました。",
    statusSegmentDeleted: "セグメントを削除しました。",
    statusAllSegmentsDeleted: "全てのセグメントが削除されました。",
    statusPreviewingSegment: "区間プレビュー中: %startTime% - %endTime%",
    errorSplitPointTooEarly: "新しい分割点は前の分割点の終了 (%time%) より後にしてください。",
    errorFixedLengthPositive: "固定長セグメントの長さは正の数値で指定してください。",
    errorFixedOffsetPositive: "開始オフセットは0以上の数値で指定してください。",
    errorFixedOffsetExceedsDuration: "開始オフセットが動画の長さを超えています。",
    statusFixedSegmentsMarked: "%count%個の固定長セグメント (長さ:%length%s, オフセット:%offset%s) をマークしました。",
    noMarkedSegments: "マークされたセグメントはありません。",
    segmentStartTimeLabelShort: "始:",
    segmentEndTimeLabelShort: "終:",
    saveButton: "保存",
    cancelButton: "中止", // Or more specific like cancelEditButton if contextually different
    segmentStatusMarked: "(マーク済)",
    segmentStatusEditing: "(編集中)",
    segmentStatusGenerating: "(生成中...)",
    segmentStatusGenerated: "(%sizeMB% MB)",
    segmentStatusFailed: "(生成失敗)",
    segmentStatusCancelled: "(キャンセル済)",
    previewButton: "プレビュー",
    editTimeButton: "時間編集",
    generateThisSegmentButton: "この区間を生成",
    regenerateSegmentButton: "再生成",
    downloadButton: "ダウンロード",
    deleteButton: "削除",
    statusAudioModeOn: "音声のみモードがオンになりました。",
    statusAudioModeOff: "音声のみモードがオフになりました。",

    statusExported: "区間情報をエクスポートしました: %fileName%",
    statusImported: "%count% 個の区間を読み込みました。",
    errorImportFormat: "エラー: ファイル形式が無効か、区間データが破損しています。",
    errorImportValidation: "エラー: 読み込んだ区間データに無効な値が含まれています。",
    statusGeneratingSegment: "区間 %segmentNumber% (%startTime% - %endTime%) を生成中...",
    statusSegmentGeneratedSuccessfully: "区間 %segmentNumber% の生成完了: %fileName%",
    statusSegmentGenerationFailed: "区間 %segmentNumber% の生成に失敗しました: %error%",
    statusAllSegmentsGenerated: "全てのマーク済みセグメントの処理が完了しました。",
    statusZipping: "ZIPファイルを生成中... (%count%個のファイル)",
    statusZipReady: "ZIPファイルの準備ができました: %fileName%",
    statusZipFailed: "ZIPファイルの生成に失敗しました: %error%",
    confirmCancelOperation: "現在の操作をキャンセルしてもよろしいですか？"
  },
  en: {
    // From HTML
    pageTitle: "Multifunctional Video Splitter v2.6 (Shortcut & Scroll Support)",
    mainHeading: "Multifunctional Video Splitter v2.2",
    fileDropAreaText: "Drag & drop video/audio files here, or click to select",
    playButton: "Play",
    playPauseButtonTitle: "Play/Pause (Space)",
    seekBarTitle: "Seek Bar",
    sequentialModeTabCaption: "Sequential Split",
    sequentialModeTabTitle: "Sequential Split Mode",
    freeModeTabCaption: "Free Interval",
    freeModeTabTitle: "Free Interval Mode",
    fixedLengthModeTabCaption: "Fixed Length Split",
    fixedLengthModeTabTitle: "Fixed Length Split Mode",
    sequentialModeHeading: "Sequential Split Mode",
    sequentialModeDescription: "Play the video and press the button below or the <kbd>M</kbd> key at the points you want to split.",
    markSequentialSplitPointButtonCaption: "Mark Split Point at Current Position",
    markSequentialSplitPointButtonTitle: "Mark split point at current position (M)",
    freeModeHeading: "Free Interval Mode",
    freeModeDescription: "Add a new segment with the button below or press the <kbd>N</kbd> key, then edit the start/end times.",
    addFreeSegmentButtonCaption: "Add New Segment",
    addFreeSegmentButtonTitle: "Add new segment (N)",
    fixedLengthModeHeading: "Fixed Length Split Mode",
    fixedSegmentLengthLabel: "Segment Length (seconds):",
    fixedStartOffsetLabel: "Start Offset (seconds):",
    previewFixedLengthSegmentsButtonCaption: "Mark Fixed Length Segments",
    commonSettingsHeading: "Common Settings",
    fileNamePrefixLabel: "Filename Prefix:",
    audioOnlyModeCheckboxLabel: " Extract and split audio only",
    audioOnlyModeCheckboxTitle: "Extract audio only (O)",
    markedSegmentsListHeading: "Marked Segments List",
    generateAllMarkedButtonCaption: "Generate All Marked Segments",
    generateAllMarkedButtonTitle: "Generate all marked, ungenerated segments",
    downloadAllGeneratedButtonCaption: "Download All Generated Segments as ZIP",
    downloadAllGeneratedButtonTitle: "Download all generated segments as a ZIP file",
    cancelCurrentOperationButtonCaption: "Cancel Current Operation",
    cancelCurrentOperationButtonTitle: "Cancel current generation/compression process (Esc)",
    statusInitial: "Status: Please select a video file.",
    exportSegmentsButtonCaption: "Export Segments Info",
    exportSegmentsButtonTitle: "Save current segment information to a file (Cmd/Ctrl + S)",
    importSegmentsLabelCaption: "Import Segments Info",
    importSegmentsLabelTitle: "Load segment information from a file (Cmd/Ctrl + O)",
    shortcutHelpText: "Shortcuts: Space (Play/Pause), M (Sequential Mark), N (New Segment), Esc (Cancel)",
    languageSelectorLabel: "Language:",
    langOptionJapanese: "Japanese",
    langOptionEnglish: "English",

    // Dynamically generated/updated by JavaScript
    pauseButton: "Pause",
    statusSelectedFile: "Selected file: %fileName%",
    statusVideoLoaded: "Video loaded: %fileName% (%duration%). Select a split mode and start.",
    errorVideoLoadFailed: "Error: Failed to load video file.",
    tooltipSegmentRange: "Segment %segmentIndex%: %startTime% - %endTime%",
    timelineMarkerStartTimeTitle: "Segment Start: %time%",
    timelineMarkerEndTimeTitle: "Segment End: %time%",
    errorInvalidStartEndTimes: "Start/End times are invalid numbers.",
    errorEndTimeBeforeStartTime: "End time (%endTime%) must be after start time (%startTime%).",
    errorStartTimeNegative: "Start time must be 0 seconds or greater.",
    errorEndTimeExceedsDuration: "End time exceeds video duration (%duration%).",
    statusErrorPrefix: "Error: %error%",
    statusSegmentAdded: "Segment (%startTime% - %endTime%) added.",
    statusSegmentUpdated: "Segment (%startTime% - %endTime%) updated.",
    statusSegmentDeleted: "Segment deleted.",
    statusAllSegmentsDeleted: "All segments deleted.",
    statusPreviewingSegment: "Previewing segment: %startTime% - %endTime%",
    errorSplitPointTooEarly: "New split point must be after the end of the previous segment (%time%).",
    errorFixedLengthPositive: "Fixed segment length must be a positive number.",
    errorFixedOffsetPositive: "Start offset must be zero or a positive number.",
    errorFixedOffsetExceedsDuration: "Start offset exceeds video duration.",
    statusFixedSegmentsMarked: "%count% fixed-length segments (length: %length%s, offset: %offset%s) marked.",
    noMarkedSegments: "No segments marked.",
    segmentStartTimeLabelShort: "Start:",
    segmentEndTimeLabelShort: "End:",
    saveButton: "Save",
    cancelButton: "Cancel",
    segmentStatusMarked: "(Marked)",
    segmentStatusEditing: "(Editing)",
    segmentStatusGenerating: "(Generating...)",
    segmentStatusGenerated: "(%sizeMB% MB)",
    segmentStatusFailed: "(Failed)",
    segmentStatusCancelled: "(Cancelled)",
    previewButton: "Preview",
    editTimeButton: "Edit Times",
    generateThisSegmentButton: "Generate This Segment",
    regenerateSegmentButton: "Regenerate",
    downloadButton: "Download",
    deleteButton: "Delete",
    statusAudioModeOn: "Audio-only mode turned ON.",
    statusAudioModeOff: "Audio-only mode turned OFF.",

    statusExported: "Exported segment information to: %fileName%",
    statusImported: "Imported %count% segments.",
    errorImportFormat: "Error: Invalid file format or corrupted segment data.",
    errorImportValidation: "Error: Imported segment data contains invalid values.",
    statusGeneratingSegment: "Generating segment %segmentNumber% (%startTime% - %endTime%)...",
    statusSegmentGeneratedSuccessfully: "Segment %segmentNumber% generated successfully: %fileName%",
    statusSegmentGenerationFailed: "Failed to generate segment %segmentNumber%: %error%",
    statusAllSegmentsGenerated: "Finished processing all marked segments.",
    statusZipping: "Generating ZIP file... (%count% files)",
    statusZipReady: "ZIP file ready: %fileName%",
    statusZipFailed: "Failed to generate ZIP file: %error%",
    confirmCancelOperation: "Are you sure you want to cancel the current operation?"
  }
};
